### ISSUE TITLE
Emacs 24 support

### ISSUE THREAD

**Issue by stephenjbarr** [ColemanGariety/toy-chest-theme#1]
Hello!

Nice looking theme. Any plans for an Emacs 24 port? I specifically mention Emacs 24 (the latest version) because that version includes substantial changes to Emacs' themeing engine.

See:
http://batsov.com/articles/2012/02/19/color-theming-in-emacs-reloaded/

Anyway, nice theme! Perhaps someone will port it.

**Comment by ColemanGariety** [comment]
Vim first, since I use that, then emacs.

**Comment by stephenjbarr** [comment]
Excellent. Thank you for letting me know.
