### ISSUE TITLE
Sublime Text 3 Colors

### ISSUE THREAD

**Issue by nanoxd** [ColemanGariety/toy-chest-theme#7]
I tried inputting the same file that was used in Coda to verify the color scheme was indeed correct and the methods were never highlighted yellow like in the demo. Is this a bug or lack of functionality on Sublime's part?

![screen shot 2013-05-18 18 10 18 0000](https://f.cloud.github.com/assets/1889575/521961/78b7b40e-bfe6-11e2-9c6d-a2daa8c05e2e.png)

Thanks for the theme.

**Comment by ColemanGariety** [comment]
This is a lack of functionality in sublime's ruby highlighting.

**Comment by nanoxd** [comment]
Thanks for the update.
